### ISSUE TITLE
주제 정하기

### ISSUE THREAD

**Issue by wooginie** [wooginie/we-expect-A-#1]
차별성에 대해 토론

**Comment by whiskend** [comment]
사람들의 눈매 길이, 눈 폭, 입술 두께, 입술 길이, 코 높이, 귀 길이, 그 사람의 학점 데이터 값을 모아서 학점 예측

**Comment by whiskend** [comment]
2024 하계 올림픽 메달 개수 예측

**Comment by sh9125** [comment]
2026년 월드컵 국가별 순위 예측

**Comment by whiskend** [comment]
식재료(대파, 양파, 고기 등)를 사와서 냉장고에 넣고 프로그램에 해당 재료를 입력하면, 상하는 날짜를 알려주고 식재료 종류 별로 표를 정리해서 분류

**Comment by sh9125** [comment]
잉글랜드 프리미어리그 팀별로 각각 승무패 예측

**Comment by whiskend** [comment]
승무패를 예측하고 그에 대한 승률을 바탕으로 토토 배당률이 타당한지 프로그램이 판단

**Comment by sh9125** [comment]
epl은 범위가 너무 넓으니까 k리그로 하는게 어떨까요?

**Comment by wooginie** [comment]
k리그는 epl과 다르게 총 12개의 팀으로 구성되어있고 그렇게 하는게 좋을거같아요. 분석은 어떤식으로 하는게 좋을까요?

**Comment by whiskend** [comment]
주제는 k리그 승무패 예측으로 정해진 것 같고 세부적인 걸 회의 해보도록 해요 ㅎㅎ
