### ISSUE TITLE
함수 이름 정하기

### ISSUE THREAD

**Issue by sh9125** [wooginie/we-expect-A-#13]
각자 맡은 부분 코드 구현할 때 만드셨던 함수 이름이랑 기능을 알려주세요

**Comment by whiskend** [comment]
//우진
void print_main();
void print_talk();
void bring_teaminfo1(NEXT* team);
void bring_allteaminfo1(NEXT** teams);
void print_mains();
//다같이
void Cursor(bool flag, int size);
void menu_display();
void move(int m, int n);
void run(int x, int y);
void gotoxy(int x, int y);
//경근
void matchData(char* dataName, DATA list_game[]);
void prediction(DATA list_game[]);
//승환
void show_teaminfo(INFO* team);
void select_team(INFO** teams);
INFO** read_Teaminfo(const char* filename);
void free_Teaminfo(INFO** list_team);
void play_quiz(Quiz* a);
void read_quizFile(FILE* file, Quiz* list_quiz, int totalQuizNum);
