### ISSUE TITLE
경기 전적 데이터 분석하는 법

### ISSUE THREAD

**Issue by whiskend** [wooginie/we-expect-A-#19]
지난 경기 전적 데이터를 csv 파일로 관리하기로 했다.
이 데이터를 가지고 어떻게 다음 경기를 예측할 수 있을까?

**Comment by snsthqhr** [comment]
계산 제가 할까요

**Comment by whiskend** [comment]
확률을 출력하는 것 이상으로 예측에 도움이 되는 근거를 찾고 싶었으나 실패
