### ISSUE TITLE
자료 관련 회의

### ISSUE THREAD

**Issue by sh9125** [wooginie/we-expect-A-#2]
세부 주제 정하기 및 요구사항 분석을 해볼까요?

**Comment by whiskend** [comment]
데이터 수집은 어떻게 할까요?

**Comment by wooginie** [comment]
세부주제는 전 이슈에서 이야기 했듯이 k리그 승무패관련해서 하면될거같고 데이터 수집같은 경우는 k리그 승무패 3년치 결과를 k리그 홈페이지에서 분석하면 될거같아요. 어떤식으로 할까요?

**Comment by sh9125** [comment]
3년치는 데이터가 너무 적은 거 같고 5년치 정도로 하는게 좋을 거 같아요. 그럼 각 팀별로 상대 전적을 통한 승무패 확률을 구하는 건가요?

**Comment by wooginie** [comment]
총 5년치면 k리그 같은경우 찾아보니 1시즌 리그 한팀당 33경기+플레이오프 포함하면 38경기를 치루게되는데 그렇게되면 38x12팀/2이기에 한시즌에 이뤄지는 총 경기수는 278경기입니다. 278경기x5시즌 하면 1390경기를 가지고 분석을 할 건데 어떤식으로 역할분담하면 좋을지 얘기 부탁드립니다.

**Comment by whiskend** [comment]
1명이 전부 분석하는 것은 어려울 것 같기 때문에 wooginie님이 18-19 시즌 분석해주시고 sh9125 20-21 시즌 분석 해주시고 제가 22 시즌 분석 할게요~

**Comment by sh9125** [comment]
그럼 각자 맡은 부분 조사하는 걸로 하고 이번 이슈는 닫겠습니다.
