### ISSUE TITLE
요구 사항 분석

### ISSUE THREAD

**Issue by whiskend** [wooginie/we-expect-A-#3]
프로젝트의 목표와 프로젝트에 필요한 기능을 파악해봅시다. 그 외로 추가적인 요구사항도 제시 가능합니다.

**Comment by wooginie** [comment]
k리그는 총 12팀으로 구성되어있는데 사용자가 두팀을 입력하면 그 두팀의 승무패 데이터를 가지고 승무패 확률을 제공해주는 기능은 어떤가요?

**Comment by whiskend** [comment]
사용자가 추가로 토토 사이트의 배당률을 입력하면, 그 배당률이 적합한지 판단해주는 기능은 어떨까요?

**Comment by wooginie** [comment]
그러면 1. 매우 위험 2. 위험 3. 보통 4. 안전 5. 매우 안전 이런식으로 확률에 따라 합법 토토를 이용하는 사용자에게 정보를 제공해주는것도 괜찮은거 같아요

**Comment by whiskend** [comment]
오 좋네요

**Comment by sh9125** [comment]
팀별로 핵심 선수가 누가 있는지랑 그 팀을 소개 해주는 기능을 넣는 건 어떤가요??

**Comment by sh9125** [comment]
그럼 확률을 가지고 판단을 할 때 필요한 기준을 어떻게 할지 정해야겠네요

**Comment by wooginie** [comment]
기준같은경우는 1%~20%(매우 위험) 21%~40%(위험) 40%~59%(보통) 60%~79%(안전) 80%~99%(매우 안전)로 하면될거같아요.

**Comment by sh9125** [comment]
그럼 사용자가 배당률을 입력하는게 아니라 우리가 예측한 확률에 따른 위험도를 사용자에게 제공하고 판단은 사용자가 하는 건가요?

**Comment by wooginie** [comment]
그렇습니다. 기존에 있는 프로그램들과 차별되는 점으로는 저희는 배당률이 아닌 위험도를 통해 사용자에게 알려주는 점으로 당연히 배당률도 승무패하는데 있어 근거가 되지만 저희는 위험도를 통해 사용자가 리스크를 걸어가면서까지 이 팀에 걸건지 아니면 안전하게 갈건지를 알려주는 프로그램입니다.

**Comment by whiskend** [comment]
좋아요 그럼 그 쪽 기능은 그렇게 하는 걸로 하죠.
그러면 수집한 데이터를 어디에 저장하고 어떻게 불러올까요?

**Comment by wooginie** [comment]
파일 입출력으로 하는건 어떻게 생각하세요?

**Comment by whiskend** [comment]
좋습니다 데이터 입출력은 그쪽으로 진행해보죠

**Comment by sh9125** [comment]
그럼 저희가 하는 기능은  1. 두 팀 사이의 승무패 예측 (위험도 제공), 2. 다음 시즌 예측, 3. 팀 소개 및 핵심 선수 소개 이정도로 하는 걸로 하고 더 추가해야 할게 있으면 다음 이슈에서 얘기 나누겠습니다.
