### ISSUE TITLE
중간 발표 준비 과정

### ISSUE THREAD

**Issue by wooginie** [wooginie/we-expect-A-#4]
발표순서
필요성: 이 프로젝트가 왜 중요한지?
problem: 
차별성: 말그대로 차별성
solution: 구현방향 어떤 언어 어떤 툴 사용하는지 현재까지의 구현 상황
추진 방법 및 일정: 언제 만나서 했는지 언제 할지 언제 완성될지
입니다.

**Comment by whiskend** [comment]
필요성에 대해 제 생각을 말해볼게요

1. 현재 k리그에 대한 관심 그다지 높지 않음 -> 사람들의 관심도를 유지하고 더 높게 해야 한다.

2. 합법 토토 이용자들이 배팅을 할 때 필요한 k리그 정보를 제공.

3. K리그 정보를 한눈에 볼 수 있는 곳이 많이 없다.

**Comment by sh9125** [comment]
좋습니다.
problem 부분에서는 k리그를 홈페이지를 제외하곤 정보를 제공해주는 곳이 적기 때문에 우리가 만든 프로그램을 통해 현재 k리그 팬들과 기존 k리그 팬들에게 k리그에 대한 정보를 제공해 줄 수 있다는 것을 말하면 될 것 같습니다.

**Comment by wooginie** [comment]
나이스.

**Comment by wooginie** [comment]
차별성같은경우는 현재 시즌 말고 다음 시즌 최종 순위를 예측하는거랑
미니게임(응원가 및 핵심 선수 맞추기, 태클 피하기 게임)을 추가하여 재미요소를 넣으면 좋을거같아요.

**Comment by whiskend** [comment]
그렇게 진행하시죠

**Comment by sh9125** [comment]
합법 토토 이용자들이 필요한 정보를 제공해주는 곳이 적은데 우리 프로그램을 사용하면 두 팀간 승무패 확률을 제공하여 예측하는데 도움을 준다는 것도 problem 부분에서 말해주면 좋을 거 같아요

**Comment by wooginie** [comment]
샤샷.

**Comment by wooginie** [comment]
발표 대본 같은경우 추후에 또 얘기해보는걸로해요.

**Comment by wooginie** [comment]
프레젠테이션에 내용 옮겨놓도록 하겠습니다.
