### ISSUE TITLE
18~22 시즌 K리그 자료 조사

### ISSUE THREAD

**Issue by whiskend** [wooginie/we-expect-A-#5]
프로그램에 들어갈 데이터 모아볼게요~

**Comment by wooginie** [comment]
전북           
울산 2승 3무 3패 
대구 4승 2무 1패
제주 3승 3무 2패
수원fc 3승 2무 2패
수원 6승 0무 1패
서울 4승 2무 0패
인천 4승 2무 1패
포항 4승 1무 2패
성남 5승 1무 0패
강원 4승 2무 1패
김천 3승 2무 1패
광주 5승 1무

울산
대구 4승 1무 2패
제주 4승 3무 1패
수원fc 6승 0무 1패
수원 3승 2무 2패
서울 4승 2무 0패
인천 3승 4무 0패
포항 3승 2무 2패
성남 2승 2무 2패
강원 6승 1무 0패
김천 5승 1무 0패
광주 4승 2무

대구
제주 3승 3패 1패
수원fc 3승 4무 1패
수원 4승 2무 2패
서울 3승 2무 2패
인천 1승 1무 4패
포항 1승 4무 1패
성남 3승 4무 0패
강원 2승 0무 4패
김천 1승 4무 2패
광주 3승 1무 2패

제주
수원fc 2승 2무 3패
수원 3승 2무 2패
서울 4승 1무 0패
인천 3승 1무 3패
포항 4승 2무 1패
성남 3승 2무 1패
강원 0승 4무 3패

김천 2승 0무 5패(주작)
광주 3승 2무 6패(주작)


수원fc(주작)
수원 4승 3무 0패
서울 2승 2무 2패
인천 1승 4무 1패
포항 2승 0무 4패
성남 3승 1무 3패
강원 4승 1무 1패

김천 8승 5무 0패(주작)
광주 4승 1무 4패(주작)

수원
서울 2승 1무 4패
인천 1승 3무 2패
포항 1승 3무 2패
성남 5승 1무 1패
강원 1승 3무 2패
김천 2승 2무 2패
광주 3승 1무 1패

서울
인천 1승 3무 3패
포항 4승 2무 1패
성남 2승 3무 3패
강원 2승 3무 2패
김천 2승 2무 2패
광주 4승 2무 0패

인천
포항 1승 4무 3패
성남 4승 1무 2패
강원 3승 2무 3패
김천 2승 1무 2패
광주 1승 1무 4패

포항
성남 3승 1무 3패
강원 5승 2무 1패
김천 4승 1무 1패
광주 5승 1무 1패

성남
강원 1승 1무 5패
김천 0승 3무 3패
광주 1승 1무 2패

강원
김천 1승 1무 3패
광주 2승 2무 2패

**Comment by wooginie** [comment]
전북           
울산 2승 3무 3패 
대구 4승 2무 1패
제주 3승 3무 2패
수원fc 3승 2무 2패
수원 6승 0무 1패
서울 4승 2무 0패
인천 4승 2무 1패
포항 4승 1무 2패
성남 5승 1무 0패
강원 4승 2무 1패
김천 3승 2무 1패
광주 5승 1무

울산
대구 4승 1무 2패
제주 4승 3무 1패
수원fc 6승 0무 1패
수원 3승 2무 2패
서울 4승 2무 0패
인천 3승 4무 0패
포항 3승 2무 2패
성남 2승 2무 2패
강원 6승 1무 0패
김천 5승 1무 0패
광주 4승 2무

대구
제주 3승 3패 1패
수원fc 3승 4무 1패
수원 4승 2무 2패
서울 3승 2무 2패
인천 1승 1무 4패
포항 1승 4무 1패
성남 3승 4무 0패
강원 2승 0무 4패
김천 1승 4무 2패
광주 3승 1무 2패

제주
수원fc 2승 2무 3패
수원 3승 2무 2패
서울 4승 1무 0패
인천 3승 1무 3패
포항 4승 2무 1패
성남 3승 2무 1패
강원 0승 4무 3패

김천 2승 0무 5패
광주 3승 2무 6패


수원fc
수원 4승 3무 0패
서울 2승 2무 2패
인천 1승 4무 1패
포항 2승 0무 4패
성남 3승 1무 3패
강원 4승 1무 1패

김천 8승 5무 0패
광주 4승 1무 4패

수원
서울 2승 1무 4패
인천 1승 3무 2패
포항 1승 3무 2패
성남 5승 1무 1패
강원 1승 3무 2패
김천 2승 2무 2패
광주 3승 1무 1패

서울
인천 1승 3무 3패
포항 4승 2무 1패
성남 2승 3무 3패
강원 2승 3무 2패
김천 2승 2무 2패
광주 4승 2무 0패

인천
포항 1승 4무 3패
성남 4승 1무 2패
강원 3승 2무 3패
김천 2승 1무 2패
광주 1승 1무 4패

포항
성남 3승 1무 3패
강원 5승 2무 1패
김천 4승 1무 1패
광주 5승 1무 1패

성남
강원 1승 1무 5패
김천 0승 3무 3패
광주 1승 1무 2패

강원
김천 1승 1무 3패
광주 2승 2무 2패

**Comment by wooginie** [comment]
전북           
울산 2승 3무 3패 
승 25% 무 37.5% 패 37.5% 
대구 4승 2무 1패
제주 3승 3무 2패
수원fc 3승 2무 2패
수원 6승 0무 1패
서울 4승 2무 0패
인천 4승 2무 1패
포항 4승 1무 2패
성남 5승 1무 0패
강원 4승 2무 1패
김천 3승 2무 1패
광주 5승 1무

울산
대구	4승	1무	2패
제주 4승 3무 1패
수원fc 6승 0무 1패
수원 3승 2무 2패
서울 4승 2무 0패
인천 3승 4무 0패
포항 3승 2무 2패
성남 2승 2무 2패
강원 6승 1무 0패
김천 5승 1무 0패
광주 4승 2무

대구
제주 3승 3패 1패
수원fc 3승 4무 1패
수원 4승 2무 2패
서울 3승 2무 2패
인천 1승 1무 4패
포항 1승 4무 1패
성남 3승 4무 0패
강원 2승 0무 4패
김천 1승 4무 2패
광주 3승 1무 2패

제주
수원fc 2승 2무 3패
수원 3승 2무 2패
서울 4승 1무 0패
인천 3승 1무 3패
포항 4승 2무 1패
성남 3승 2무 1패
강원 0승 4무 3패

김천 2승 0무 5패(주작)
광주 3승 2무 6패(주작)


수원fc(주작)
수원 4승 3무 0패
서울 2승 2무 2패
인천 1승 4무 1패
포항 2승 0무 4패
성남 3승 1무 3패
강원 4승 1무 1패

김천 8승 5무 0패(주작)
광주 4승 1무 4패(주작)

수원
서울 2승 1무 4패
인천 1승 3무 2패
포항 1승 3무 2패
성남 5승 1무 1패
강원 1승 3무 2패
김천 2승 2무 2패
광주 3승 1무 1패

서울
인천 1승 3무 3패
포항 4승 2무 1패
성남 2승 3무 3패
강원 2승 3무 2패
김천 2승 2무 2패
광주 4승 2무 0패

인천
포항 1승 4무 3패
성남 4승 1무 2패
강원 3승 2무 3패
김천 2승 1무 2패
광주 1승 1무 4패

포항
성남 3승 1무 3패
강원 5승 2무 1패
김천 4승 1무 1패
광주 5승 1무 1패

성남
강원 1승 1무 5패
김천 0승 3무 3패
광주 1승 1무 2패

강원
김천 1승 1무 3패
광주 2승 2무 2패
