### ISSUE TITLE
팀에 관한 정보 제공 범위 정하기

### ISSUE THREAD

**Issue by sh9125** [wooginie/we-expect-A-#6]
팀 정보를 제공할 때 저희가 제공하는 정보의 범위를 어디까지 할까요??

**Comment by wooginie** [comment]
정보같은경우는 핵심 선수, 응원가, 구단역사 등 하면 될거같아요

**Comment by whiskend** [comment]
조하요

**Comment by sh9125** [comment]
그럼 제가 자료 조사할 때 팀의 핵심 선수, 구단 역사, 팀 응원가 이 세가지만 조사하면 될까요??

**Comment by wooginie** [comment]
세가지로 일단 생각해두고 추가할거 있으면 말씀드릴게요

**Comment by sh9125** [comment]
토의 결과 팀 정보가 팀 이름, 유니폼, 마스코트, 홈 구장, 역사, 감독, 주장, 공격수, 미드필더, 수비수, 골키퍼, 응원가, 지난 시즌 순위, 엠블럼 이렇게 구성되는 걸로 결정 났습니다. 이슈 닫겠습니다.
